{
  "hash": "e12b1756f8eb53bf6b1e9c4893343929",
  "result": {
    "markdown": "---\ntitle: \"Day3 - Here We R! - Regression using R\"\nauthor: \"Kamran Khan & Didjier Masangwi\"\ninstitution: \"PCTU Queen Mary University of London\"\ndate: today\ntitle-slide-attributes:\n  data-background-image: images/hello-quarto.png\n  data-background-size: stretch\n  data-background-opacity: \"0.5\"\nformat:\n  revealjs:\n    transition: slide\n    echo: true\n    code-fold: true\n    background-transition: fade\nrevealjs-plugins:\n  - drop\neditor: visual\nembed-resources: true\n---\n\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# List of required packages\nrequired_packages <- c(\"tidyverse\", \"survival\", \"survminer\", \n                       \"ggplot2\", \"labelled\", \"gtsummary\", \"labelled\", \n                       \"purrr\", \"here\", \"EnvStats\", \"rstatix\")\n\n# Check and install missing packages\ninstall_if_missing <- function(packages) {\n  missing <- packages[!packages %in% installed.packages()[, \"Package\"]]\n  if (length(missing) > 0) {\n    install.packages(missing, dependencies = TRUE) # Include dependencies\n    message(\"Installed missing packages: \", paste(missing, collapse = \", \"))\n  } else {\n    message(\"All required packages are already installed.\")\n  }\n}\n\n# Run the function\ninstall_if_missing(required_packages)\n```\n:::\n\n\n## Loading the required libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(survminer)\nlibrary(ggplot2)\nlibrary(gtsummary)\nlibrary(labelled)\nlibrary(purrr)\nlibrary(here)\nlibrary(EnvStats)\nlibrary(rstatix)\n```\n:::\n\n\n## Create a clinical dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)  # For reproducibility\nclinical_trial_data <- tibble(\n  patient_id = 1:150,\n  age = rnorm(150, mean = 50, sd = 12),  # Patient age\n  sex = sample(c(\"Male\", \"Female\"), 150, replace = TRUE),  # Patient sex\n  treatment_group = sample(c(\"Control\", \"Treatment A\", \"Treatment B\"), 150, replace = TRUE),  # Treatment groups\n  time_to_event = rexp(150, rate = 0.1),  # Time to event (survival data)\n  event_occurred = sample(c(0, 1), 150, replace = TRUE),  # Event status (0 = censored, 1 = event occurred)\n  baseline_score = rnorm(150, mean = 75, sd = 10),  # Baseline health score\n  followup_score = rnorm(150, mean = 80, sd = 10)  # Follow-up health score\n)\n\n#Inspect the data \n\nglimpse(clinical_trial_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 150\nColumns: 8\n$ patient_id      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…\n$ age             <dbl> 43.27429, 47.23787, 68.70450, 50.84610, 51.55145, 70.5…\n$ sex             <chr> \"Female\", \"Female\", \"Male\", \"Female\", \"Male\", \"Male\", …\n$ treatment_group <chr> \"Treatment A\", \"Control\", \"Treatment A\", \"Control\", \"T…\n$ time_to_event   <dbl> 4.2537311, 14.3825042, 16.4363696, 2.9411470, 17.74436…\n$ event_occurred  <dbl> 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, …\n$ baseline_score  <dbl> 80.50044, 87.36676, 76.39098, 79.10275, 69.41543, 81.0…\n$ followup_score  <dbl> 60.38292, 68.80100, 66.72245, 71.46376, 73.06695, 83.8…\n```\n:::\n:::\n\n\n## Data Manipulation and Visualization with tidyverse\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclinical_trial_data <- clinical_trial_data |> \n  mutate(Group = factor(treatment_group))\n\nglimpse(clinical_trial_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 150\nColumns: 9\n$ patient_id      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…\n$ age             <dbl> 43.27429, 47.23787, 68.70450, 50.84610, 51.55145, 70.5…\n$ sex             <chr> \"Female\", \"Female\", \"Male\", \"Female\", \"Male\", \"Male\", …\n$ treatment_group <chr> \"Treatment A\", \"Control\", \"Treatment A\", \"Control\", \"T…\n$ time_to_event   <dbl> 4.2537311, 14.3825042, 16.4363696, 2.9411470, 17.74436…\n$ event_occurred  <dbl> 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, …\n$ baseline_score  <dbl> 80.50044, 87.36676, 76.39098, 79.10275, 69.41543, 81.0…\n$ followup_score  <dbl> 60.38292, 68.80100, 66.72245, 71.46376, 73.06695, 83.8…\n$ Group           <fct> Treatment A, Control, Treatment A, Control, Treatment …\n```\n:::\n:::\n\n\n## Select specific columns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select specific columns\nselected_data <- clinical_trial_data %>% \n  select(patient_id, age, treatment_group, baseline_score, followup_score)\n\n\nhead(selected_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  patient_id   age treatment_group baseline_score followup_score\n       <int> <dbl> <chr>                    <dbl>          <dbl>\n1          1  43.3 Treatment A               80.5           60.4\n2          2  47.2 Control                   87.4           68.8\n3          3  68.7 Treatment A               76.4           66.7\n4          4  50.8 Control                   79.1           71.5\n5          5  51.6 Treatment A               69.4           73.1\n6          6  70.6 Control                   81.1           83.8\n```\n:::\n:::\n\n\n## Filtering\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter patients in the Treatment A group\nfiltered_data <- clinical_trial_data %>% \n  filter(treatment_group == \"Treatment A\")\n\nhead(filtered_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 9\n  patient_id   age sex    treatment_group time_to_event event_occurred\n       <int> <dbl> <chr>  <chr>                   <dbl>          <dbl>\n1          1  43.3 Female Treatment A              4.25              1\n2          3  68.7 Male   Treatment A             16.4               0\n3          5  51.6 Male   Treatment A             17.7               1\n4          8  34.8 Male   Treatment A             24.6               0\n5         11  64.7 Female Treatment A              1.75              1\n6         13  54.8 Female Treatment A             20.0               0\n# ℹ 3 more variables: baseline_score <dbl>, followup_score <dbl>, Group <fct>\n```\n:::\n:::\n\n\n## Mutate\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a new variable for change in health score\nclinical_trial_data <- clinical_trial_data %>%\n  mutate(score_change = followup_score - baseline_score)\n\nncol(clinical_trial_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10\n```\n:::\n\n```{.r .cell-code}\nnames(clinical_trial_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"patient_id\"      \"age\"             \"sex\"             \"treatment_group\"\n [5] \"time_to_event\"   \"event_occurred\"  \"baseline_score\"  \"followup_score\" \n [9] \"Group\"           \"score_change\"   \n```\n:::\n:::\n\n\n## Plotting with ggplot2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boxplot of follow-up scores by treatment group\nggplot(clinical_trial_data, aes(x = age, y = Group)) +\n  geom_point() +\n  labs(title = \"Follow-up Scores by Treatment Group\", x = \"Treatment Group\", y = \"Follow-up Score\")\n```\n\n::: {.cell-output-display}\n![](Day3_Kam_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n# Statistics using R\n\n## T-test\n\nTwo sample t-test (Student's t-test) can be used if we have two independent (unrelated) groups (e.g., males-females, treatment-non treatment) and one quantitative variable of interest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for Control and Treatment A groups\nt_test_data <- clinical_trial_data |> \n  filter(treatment_group %in% c(\"Control\", \"Treatment A\"))\n\nhead(t_test_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 10\n  patient_id   age sex    treatment_group time_to_event event_occurred\n       <int> <dbl> <chr>  <chr>                   <dbl>          <dbl>\n1          1  43.3 Female Treatment A              4.25              1\n2          2  47.2 Female Control                 14.4               1\n3          3  68.7 Male   Treatment A             16.4               0\n4          4  50.8 Female Control                  2.94              0\n5          5  51.6 Male   Treatment A             17.7               1\n6          6  70.6 Male   Control                 37.5               1\n# ℹ 4 more variables: baseline_score <dbl>, followup_score <dbl>, Group <fct>,\n#   score_change <dbl>\n```\n:::\n:::\n\n\n## Perform t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform t-test\nt.test(followup_score ~ treatment_group, data = t_test_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  followup_score by treatment_group\nt = -0.84913, df = 74.638, p-value = 0.3985\nalternative hypothesis: true difference in means between group Control and group Treatment A is not equal to 0\n95 percent confidence interval:\n -5.838296  2.348822\nsample estimates:\n    mean in group Control mean in group Treatment A \n                 77.43787                  79.18261 \n```\n:::\n:::\n\n\n## Presenting the results using gtsummary package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_test_reults <- t_test_data |>  \n  select(treatment_group,followup_score) |> \n  tbl_summary(\n    by = treatment_group, \n    statistic = followup_score ~ \"{mean} ({sd})\", \n    label = list(followup_score ~ \"Score\"),\n    missing = c(\"no\")) |>  \n    add_p(test = all_continuous() ~ \"t.test\") |> \n    bold_labels() \n \nt_test_reults\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"gdwzpdiepk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gdwzpdiepk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gdwzpdiepk thead, #gdwzpdiepk tbody, #gdwzpdiepk tfoot, #gdwzpdiepk tr, #gdwzpdiepk td, #gdwzpdiepk th {\n  border-style: none;\n}\n\n#gdwzpdiepk p {\n  margin: 0;\n  padding: 0;\n}\n\n#gdwzpdiepk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gdwzpdiepk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gdwzpdiepk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gdwzpdiepk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gdwzpdiepk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gdwzpdiepk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gdwzpdiepk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gdwzpdiepk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gdwzpdiepk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gdwzpdiepk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gdwzpdiepk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gdwzpdiepk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gdwzpdiepk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gdwzpdiepk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gdwzpdiepk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdwzpdiepk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gdwzpdiepk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gdwzpdiepk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gdwzpdiepk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdwzpdiepk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gdwzpdiepk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdwzpdiepk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gdwzpdiepk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdwzpdiepk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gdwzpdiepk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdwzpdiepk .gt_left {\n  text-align: left;\n}\n\n#gdwzpdiepk .gt_center {\n  text-align: center;\n}\n\n#gdwzpdiepk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gdwzpdiepk .gt_font_normal {\n  font-weight: normal;\n}\n\n#gdwzpdiepk .gt_font_bold {\n  font-weight: bold;\n}\n\n#gdwzpdiepk .gt_font_italic {\n  font-style: italic;\n}\n\n#gdwzpdiepk .gt_super {\n  font-size: 65%;\n}\n\n#gdwzpdiepk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gdwzpdiepk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gdwzpdiepk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gdwzpdiepk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gdwzpdiepk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gdwzpdiepk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gdwzpdiepk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gdwzpdiepk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gdwzpdiepk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"PHN0cm9uZz5Db250cm9sPC9zdHJvbmc+PGJyIC8+Ck4gPSAzOQ==\"><span class='gt_from_md'><strong>Control</strong><br />\nN = 39</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"PHN0cm9uZz5UcmVhdG1lbnQgQTwvc3Ryb25nPjxiciAvPgpOID0gNTU=\"><span class='gt_from_md'><strong>Treatment A</strong><br />\nN = 55</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Score</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">77 (10)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">79 (9)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"V2VsY2ggVHdvIFNhbXBsZSB0LXRlc3Q=\"><span class='gt_from_md'>Welch Two Sample t-test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\nWe can now save the results as .docx format\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save\n t_test_reults |>\n   as_flex_table() |>\n   flextable::save_as_docx(\n     path = here::here(\"t_test_reults_tbl.docx\")\n   )\n```\n:::\n\n\n## **Chi-sqaure test of independence**\n\nIf we want to see whether there's an association between two categorical variables we can use the Pearson's chi-square test, often called chi-square test of independence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create contingency table for sex and treatment group\ncontingency_table <- table(clinical_trial_data$sex, clinical_trial_data$treatment_group)\n\n# Perform chi-square test\nchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  contingency_table\nX-squared = 0.72972, df = 2, p-value = 0.6943\n```\n:::\n:::\n\n\n## Using gtsummary()\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclinical_trial_data |>\n  select(treatment_group, sex) |> \n  tbl_summary(by = treatment_group) |>\n  add_p() |> \n  add_n()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"xufyclaylm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xufyclaylm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xufyclaylm thead, #xufyclaylm tbody, #xufyclaylm tfoot, #xufyclaylm tr, #xufyclaylm td, #xufyclaylm th {\n  border-style: none;\n}\n\n#xufyclaylm p {\n  margin: 0;\n  padding: 0;\n}\n\n#xufyclaylm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xufyclaylm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xufyclaylm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xufyclaylm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xufyclaylm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xufyclaylm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xufyclaylm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xufyclaylm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xufyclaylm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xufyclaylm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xufyclaylm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xufyclaylm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xufyclaylm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xufyclaylm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xufyclaylm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xufyclaylm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xufyclaylm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xufyclaylm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xufyclaylm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xufyclaylm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xufyclaylm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xufyclaylm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xufyclaylm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xufyclaylm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xufyclaylm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xufyclaylm .gt_left {\n  text-align: left;\n}\n\n#xufyclaylm .gt_center {\n  text-align: center;\n}\n\n#xufyclaylm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xufyclaylm .gt_font_normal {\n  font-weight: normal;\n}\n\n#xufyclaylm .gt_font_bold {\n  font-weight: bold;\n}\n\n#xufyclaylm .gt_font_italic {\n  font-style: italic;\n}\n\n#xufyclaylm .gt_super {\n  font-size: 65%;\n}\n\n#xufyclaylm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xufyclaylm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xufyclaylm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xufyclaylm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xufyclaylm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xufyclaylm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xufyclaylm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xufyclaylm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xufyclaylm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\"><span data-qmd-base64=\"PHN0cm9uZz5OPC9zdHJvbmc+\"><span class='gt_from_md'><strong>N</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"PHN0cm9uZz5Db250cm9sPC9zdHJvbmc+PGJyIC8+Ck4gPSAzOQ==\"><span class='gt_from_md'><strong>Control</strong><br />\nN = 39</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"PHN0cm9uZz5UcmVhdG1lbnQgQTwvc3Ryb25nPjxiciAvPgpOID0gNTU=\"><span class='gt_from_md'><strong>Treatment A</strong><br />\nN = 55</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_3\"><span data-qmd-base64=\"PHN0cm9uZz5UcmVhdG1lbnQgQjwvc3Ryb25nPjxiciAvPgpOID0gNTY=\"><span class='gt_from_md'><strong>Treatment B</strong><br />\nN = 56</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"n\" class=\"gt_row gt_center\">150</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.7</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">15 (38%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">26 (47%)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">24 (43%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">24 (62%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">29 (53%)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">32 (57%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk=\"><span class='gt_from_md'>n (%)</span></span></td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"UGVhcnNvbuKAmXMgQ2hpLXNxdWFyZWQgdGVzdA==\"><span class='gt_from_md'>Pearson’s Chi-squared test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n## ANOVA\n\nThe data in *dataDWL* dataset. In this example we explore the variations between weight loss according to four different types of diet. The question that may be asked is: does the average weight loss differ according to the diet?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndataDWL <- read_excel(\"dataDWL.xlsx\")\n\ndataDWL <- dataDWL %>% \n  mutate(Diet = factor(Diet))\nglimpse(dataDWL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 60\nColumns: 2\n$ WeightLoss <dbl> 9.9, 9.6, 8.0, 4.9, 10.2, 9.0, 9.8, 10.8, 6.2, 8.3, 12.9, 1…\n$ Diet       <fct> A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, B, B, B, B, B,…\n```\n:::\n\n```{.r .cell-code}\nhead(dataDWL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  WeightLoss Diet \n       <dbl> <fct>\n1        9.9 A    \n2        9.6 A    \n3        8   A    \n4        4.9 A    \n5       10.2 A    \n6        9   A    \n```\n:::\n:::\n\n\n## **Summary statistics**\n\nThe `WeightLoss` summary statistics for each diet group are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDWL_summary <- dataDWL %>%\n  group_by(Diet) %>%\n  dplyr::summarise(\n    n = n(),\n    na = sum(is.na(WeightLoss)),\n    min = min(WeightLoss, na.rm = TRUE),\n    q1 = quantile(WeightLoss, 0.25, na.rm = TRUE),\n    median = quantile(WeightLoss, 0.5, na.rm = TRUE),\n    q3 = quantile(WeightLoss, 0.75, na.rm = TRUE),\n    max = max(WeightLoss, na.rm = TRUE),\n    mean = mean(WeightLoss, na.rm = TRUE),\n    sd = sd(WeightLoss, na.rm = TRUE),\n    skewness = EnvStats::skewness(WeightLoss, na.rm = TRUE),\n    kurtosis= EnvStats::kurtosis(WeightLoss, na.rm = TRUE)\n  ) %>%\n  ungroup()\n\nDWL_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 12\n  Diet      n    na   min    q1 median    q3   max  mean    sd skewness kurtosis\n  <fct> <int> <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1 A        15     0   4.9  8.15    9.6  10.5  12.9  9.18  2.30  -0.471    -0.302\n2 B        15     0   3.8  7.85    9.2  10.8  12.7  8.91  2.78  -0.467    -0.515\n3 C        15     0   8.7 10.8    12.2  13    15.1 12.1   1.79  -0.0451   -0.530\n4 D        15     0   5.8  9.5    10.5  11.8  13.7 10.5   2.23  -0.475     0.229\n```\n:::\n:::\n\n\n## **Run the ANOVA test**\n\nWe will perform an ANOVA to test the null hypothesis that the mean weight loss is the same for all the diet groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the analysis of variance\nanova_one_way <- aov(WeightLoss ~ Diet, data = dataDWL)\n\n# Summary of the analysis\nsummary(anova_one_way)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nDiet         3  97.33   32.44   6.118 0.00113 **\nResiduals   56 296.99    5.30                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n## Present the results using gtsummary\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt_summ_ANOVA <- dataDWL %>% \n  tbl_summary(\n    by = Diet, \n    statistic = WeightLoss ~ \"{mean} ({sd})\", \n    digits = list(everything() ~ 1), #number of decimal places (gtsummary)\n    label = list(WeightLoss ~ \"Weight Loss (kg)\"), \n    missing = c(\"no\")) |> \n  add_p(test = WeightLoss ~ \"aov\") \n\ngt_summ_ANOVA\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"knhabjbfml\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#knhabjbfml table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#knhabjbfml thead, #knhabjbfml tbody, #knhabjbfml tfoot, #knhabjbfml tr, #knhabjbfml td, #knhabjbfml th {\n  border-style: none;\n}\n\n#knhabjbfml p {\n  margin: 0;\n  padding: 0;\n}\n\n#knhabjbfml .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#knhabjbfml .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#knhabjbfml .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#knhabjbfml .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#knhabjbfml .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#knhabjbfml .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#knhabjbfml .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#knhabjbfml .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#knhabjbfml .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#knhabjbfml .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#knhabjbfml .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#knhabjbfml .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#knhabjbfml .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#knhabjbfml .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#knhabjbfml .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#knhabjbfml .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#knhabjbfml .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#knhabjbfml .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#knhabjbfml .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#knhabjbfml .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#knhabjbfml .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#knhabjbfml .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#knhabjbfml .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#knhabjbfml .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#knhabjbfml .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#knhabjbfml .gt_left {\n  text-align: left;\n}\n\n#knhabjbfml .gt_center {\n  text-align: center;\n}\n\n#knhabjbfml .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#knhabjbfml .gt_font_normal {\n  font-weight: normal;\n}\n\n#knhabjbfml .gt_font_bold {\n  font-weight: bold;\n}\n\n#knhabjbfml .gt_font_italic {\n  font-style: italic;\n}\n\n#knhabjbfml .gt_super {\n  font-size: 65%;\n}\n\n#knhabjbfml .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#knhabjbfml .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#knhabjbfml .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#knhabjbfml .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#knhabjbfml .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#knhabjbfml .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#knhabjbfml .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#knhabjbfml .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#knhabjbfml div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"PHN0cm9uZz5BPC9zdHJvbmc+PGJyIC8+Ck4gPSAxNQ==\"><span class='gt_from_md'><strong>A</strong><br />\nN = 15</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"PHN0cm9uZz5CPC9zdHJvbmc+PGJyIC8+Ck4gPSAxNQ==\"><span class='gt_from_md'><strong>B</strong><br />\nN = 15</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_3\"><span data-qmd-base64=\"PHN0cm9uZz5DPC9zdHJvbmc+PGJyIC8+Ck4gPSAxNQ==\"><span class='gt_from_md'><strong>C</strong><br />\nN = 15</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_4\"><span data-qmd-base64=\"PHN0cm9uZz5EPC9zdHJvbmc+PGJyIC8+Ck4gPSAxNQ==\"><span class='gt_from_md'><strong>D</strong><br />\nN = 15</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Weight Loss (kg)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">9.2 (2.3)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8.9 (2.8)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">12.1 (1.8)</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">10.5 (2.2)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"T25lLXdheSBhbmFseXNpcyBvZiBtZWFucw==\"><span class='gt_from_md'>One-way analysis of means</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n## **Post-hoc tests**\n\nA significant one-way ANOVA is generally followed up by post-hoc tests to perform multiple pairwise comparisons between groups\n\nThe output contains the following columns of interest:\n\n-   estimate: estimate of the difference between means of the two groups\n\n-   conf.low, conf.high: the lower and the upper end point of the confidence interval at 95% (default)\n\n-   p.adj: p-value after adjustment for the multiple comparisons.\n\n## Pairwise Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pairwise comparisons\npwc_Tukey <- dataDWL %>% \n  tukey_hsd(WeightLoss ~ Diet)\n\npwc_Tukey \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 9\n  term  group1 group2 null.value estimate conf.low conf.high   p.adj\n* <chr> <chr>  <chr>       <dbl>    <dbl>    <dbl>     <dbl>   <dbl>\n1 Diet  A      B               0   -0.273   -2.50      1.95  0.988  \n2 Diet  A      C               0    2.93     0.707     5.16  0.00513\n3 Diet  A      D               0    1.36    -0.867     3.59  0.377  \n4 Diet  B      C               0    3.21     0.980     5.43  0.0019 \n5 Diet  B      D               0    1.63    -0.593     3.86  0.222  \n6 Diet  C      D               0   -1.57    -3.80      0.653 0.252  \n# ℹ 1 more variable: p.adj.signif <chr>\n```\n:::\n:::\n\n\n## Explanation\n\nPairwise comparisons were carried out using the method of Tukey and the adjusted p-values were calculated.The results in Tukey post hoc table show that the weight loss from diet C seems to be significantly larger than diet A (mean difference = 2.91 kg, 95%CI \\[0.71, 5.16\\], p=0.005 \\<0.05) and diet B (mean difference = 3.21 kg, 95%CI \\[0.98, 5.43\\], p=0.002 \\<0.05).\n\n## Regression Analysis in R\n\n#### Linear Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a linear regression model for follow-up score\nlinear_model <- lm(followup_score ~ baseline_score + age + treatment_group, data = clinical_trial_data)\nsummary(linear_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = followup_score ~ baseline_score + age + treatment_group, \n    data = clinical_trial_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-28.3237  -6.0981   0.8911   6.7859  24.4590 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                75.65192    7.73245   9.784   <2e-16 ***\nbaseline_score              0.01460    0.08400   0.174   0.8623    \nage                         0.01309    0.07514   0.174   0.8620    \ntreatment_groupTreatment A  1.82602    2.18249   0.837   0.4042    \ntreatment_groupTreatment B  5.53946    2.12548   2.606   0.0101 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.15 on 145 degrees of freedom\nMultiple R-squared:  0.04954,\tAdjusted R-squared:  0.02332 \nF-statistic:  1.89 on 4 and 145 DF,  p-value: 0.1154\n```\n:::\n:::\n\n\n## Using the `broom::tidy()`\n\n`function to get the results in a nice tibble`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_model |> broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 5\n  term                       estimate std.error statistic  p.value\n  <chr>                         <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                 75.7       7.73       9.78  1.14e-17\n2 baseline_score               0.0146    0.0840     0.174 8.62e- 1\n3 age                          0.0131    0.0751     0.174 8.62e- 1\n4 treatment_groupTreatment A   1.83      2.18       0.837 4.04e- 1\n5 treatment_groupTreatment B   5.54      2.13       2.61  1.01e- 2\n```\n:::\n:::\n\n\n## Using gtsummary() function tbl_regression()\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tidy(linear_model)\ntbl_regression(linear_model) |> \n  bold_labels() |> \n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fjtqkhuezs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fjtqkhuezs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fjtqkhuezs thead, #fjtqkhuezs tbody, #fjtqkhuezs tfoot, #fjtqkhuezs tr, #fjtqkhuezs td, #fjtqkhuezs th {\n  border-style: none;\n}\n\n#fjtqkhuezs p {\n  margin: 0;\n  padding: 0;\n}\n\n#fjtqkhuezs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fjtqkhuezs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fjtqkhuezs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fjtqkhuezs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fjtqkhuezs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fjtqkhuezs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fjtqkhuezs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fjtqkhuezs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fjtqkhuezs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fjtqkhuezs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fjtqkhuezs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fjtqkhuezs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fjtqkhuezs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fjtqkhuezs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fjtqkhuezs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjtqkhuezs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fjtqkhuezs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fjtqkhuezs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fjtqkhuezs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjtqkhuezs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fjtqkhuezs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjtqkhuezs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fjtqkhuezs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjtqkhuezs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fjtqkhuezs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjtqkhuezs .gt_left {\n  text-align: left;\n}\n\n#fjtqkhuezs .gt_center {\n  text-align: center;\n}\n\n#fjtqkhuezs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fjtqkhuezs .gt_font_normal {\n  font-weight: normal;\n}\n\n#fjtqkhuezs .gt_font_bold {\n  font-weight: bold;\n}\n\n#fjtqkhuezs .gt_font_italic {\n  font-style: italic;\n}\n\n#fjtqkhuezs .gt_super {\n  font-size: 65%;\n}\n\n#fjtqkhuezs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fjtqkhuezs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fjtqkhuezs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fjtqkhuezs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fjtqkhuezs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fjtqkhuezs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fjtqkhuezs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fjtqkhuezs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fjtqkhuezs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5CZXRhPC9zdHJvbmc+\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">baseline_score</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.01</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.15, 0.18</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.01</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.14, 0.16</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">treatment_group</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Control</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Treatment A</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.8</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-2.5, 6.1</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Treatment B</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">5.5</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.3, 9.7</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.010</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"Q0kgPSBDb25maWRlbmNlIEludGVydmFs\"><span class='gt_from_md'>CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Logistic Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit logistic regression to predict event occurrence\nlogistic_model <- glm(event_occurred ~ age + sex + treatment_group, data = clinical_trial_data, family = binomial)\nsummary(logistic_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = event_occurred ~ age + sex + treatment_group, family = binomial, \n    data = clinical_trial_data)\n\nCoefficients:\n                           Estimate Std. Error z value Pr(>|z|)\n(Intercept)                 0.02512    0.89167   0.028    0.978\nage                         0.01190    0.01504   0.791    0.429\nsexMale                    -0.46608    0.33595  -1.387    0.165\ntreatment_groupTreatment A -0.44221    0.43921  -1.007    0.314\ntreatment_groupTreatment B -0.43374    0.42684  -1.016    0.310\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 207.92  on 149  degrees of freedom\nResidual deviance: 203.78  on 145  degrees of freedom\nAIC: 213.78\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n## Using gtsummary, function tbl_regression()\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt_summ_logReg <- tbl_regression(logistic_model, exponentiate = TRUE)\ngt_summ_logReg\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ashqnxgcax\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ashqnxgcax table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ashqnxgcax thead, #ashqnxgcax tbody, #ashqnxgcax tfoot, #ashqnxgcax tr, #ashqnxgcax td, #ashqnxgcax th {\n  border-style: none;\n}\n\n#ashqnxgcax p {\n  margin: 0;\n  padding: 0;\n}\n\n#ashqnxgcax .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ashqnxgcax .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ashqnxgcax .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ashqnxgcax .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ashqnxgcax .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ashqnxgcax .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ashqnxgcax .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ashqnxgcax .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ashqnxgcax .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ashqnxgcax .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ashqnxgcax .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ashqnxgcax .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ashqnxgcax .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ashqnxgcax .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ashqnxgcax .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ashqnxgcax .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ashqnxgcax .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ashqnxgcax .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ashqnxgcax .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ashqnxgcax .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ashqnxgcax .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ashqnxgcax .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ashqnxgcax .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ashqnxgcax .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ashqnxgcax .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ashqnxgcax .gt_left {\n  text-align: left;\n}\n\n#ashqnxgcax .gt_center {\n  text-align: center;\n}\n\n#ashqnxgcax .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ashqnxgcax .gt_font_normal {\n  font-weight: normal;\n}\n\n#ashqnxgcax .gt_font_bold {\n  font-weight: bold;\n}\n\n#ashqnxgcax .gt_font_italic {\n  font-style: italic;\n}\n\n#ashqnxgcax .gt_super {\n  font-size: 65%;\n}\n\n#ashqnxgcax .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ashqnxgcax .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ashqnxgcax .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ashqnxgcax .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ashqnxgcax .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ashqnxgcax .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ashqnxgcax .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ashqnxgcax .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ashqnxgcax div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5PUjwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>OR</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.01</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.98, 1.04</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.63</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.32, 1.21</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.2</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment_group</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Control</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Treatment A</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.64</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.27, 1.51</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.3</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Treatment B</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.65</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.28, 1.49</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.3</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"T1IgPSBPZGRzIFJhdGlvLCBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>OR = Odds Ratio, CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Save as word output for sharing\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save\n gt_summ_logReg |>\n   as_flex_table() |>\n   flextable::save_as_docx(\n     path = here::here(\"ligisticReg_tbl.docx\")\n   )\n```\n:::\n\n\nResources:\n\nR for Data Science Book\n\n<https://argoshare.is.ed.ac.uk/healthyr_book/>\n\ngtsummary website\n\n<https://www.danieldsjoberg.com/gtsummary/>\n\nR medicine conference Gtsummary webinar\n\n<https://www.youtube.com/watch?v=p-diyV2E77o>\n",
    "supporting": [
      "Day3_Kam_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}